### ISSUE TITLE
请问如何打包使用？

### ISSUE THREAD

**Issue by NealLemonade** [skyrocketingHong/Bot.QQ#3]
使用了IDEA内置的MAVEN工具构建，然而启动后闪一段文字后闪退

**Comment by NealLemonade** [comment]
打扰大佬了！

**Comment by NealLemonade** [comment]
2023-01-16 01:43:12.345  INFO 308 --- [           main] n.s.fuyao.FuyaoBotApplication            : Starting FuyaoBotApplication v4.5.20.86 using Java 17.0.5 on Lemonsuda with PID 308 (E:\TestBot\uyao\fuyao-bot-4.5.20.86.jar started by Neal in E:\TestBot\uyao)
2023-01-16 01:43:12.347  INFO 308 --- [           main] n.s.fuyao.FuyaoBotApplication            : The following 1 profile is active: "dev"
2023-01-16 01:43:13.044  INFO 308 --- [           main] c.a.d.s.b.a.DruidDataSourceAutoConfigure : Init DruidDataSource
2023-01-16 01:43:13.163  WARN 308 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'miraiBotConfig' defined in URL [jar:file:/E:/TestBot/uyao/fuyao-bot-4.5.20.86.jar!/BOOT-INF/classes!/ninja/skyrocketing/fuyao/bot/config/MiraiBotConfig.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'botConfigServiceImpl' defined in URL [jar:file:/E:/TestBot/uyao/fuyao-bot-4.5.20.86.jar!/BOOT-INF/classes!/ninja/skyrocketing/fuyao/bot/service/impl/bot/BotConfigServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'botConfigMapper' defined in URL [jar:file:/E:/TestBot/uyao/fuyao-bot-4.5.20.86.jar!/BOOT-INF/classes!/ninja/skyrocketing/fuyao/bot/mapper/bot/BotConfigMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.class]: Invocation of init method failed; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine suitable jdbc url
2023-01-16 01:43:13.169  INFO 308 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-01-16 01:43:13.197 ERROR 308 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine suitable jdbc url


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (the profiles dev are currently active).

**Comment by NealLemonade** [comment]
如果方便的话希望大佬更新到mirai 2.13.3 感激不尽

**Comment by skyrocketingHong** [comment]
@NealLemonade 你建了数据库没？

**Comment by NealLemonade** [comment]
> @NealLemonade 你建了数据库没？

2023-01-16 10:48:55.283  INFO 28060 --- [           main] n.s.fuyao.FuyaoBotApplication            : Starting FuyaoBotApplication v4.5.20.86 using Java 17.0.5 on Lemonsuda with PID 28060 (E:\TestBot\uyao\fuyao-bot-4.5.20.86.jar started by Neal in E:\TestBot\uyao)
2023-01-16 10:48:55.285  INFO 28060 --- [           main] n.s.fuyao.FuyaoBotApplication            : The following 1 profile is active: "dev"
2023-01-16 10:48:55.922  INFO 28060 --- [           main] c.a.d.s.b.a.DruidDataSourceAutoConfigure : Init DruidDataSource
2023-01-16 10:48:56.528  INFO 28060 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
 _ _   |_  _ _|_. ___ _ |    _ 
| | |\/|_)(_| | |_\  |_)||_|_\ 
     /               |         
                        3.5.2 
2023-01-16 10:48:56.891  WARN 28060 --- [           main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "ninja.skyrocketing.fuyao.bot.pojo.group.GroupMemberMessageCount".
2023-01-16 10:48:56.891  WARN 28060 --- [           main] c.b.m.core.injector.DefaultSqlInjector   : class ninja.skyrocketing.fuyao.bot.pojo.group.GroupMemberMessageCount ,Not found @TableId annotation, Cannot use Mybatis-Plus 'xxById' Method.
2023-01-16 10:48:56.893  WARN 28060 --- [           main] c.b.m.core.injector.AbstractMethod       : [ninja.skyrocketing.fuyao.bot.mapper.group.GroupMemberMessageCountMapper.insert] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Insert]
2023-01-16 10:48:56.895  WARN 28060 --- [           main] c.b.m.core.injector.AbstractMethod       : [ninja.skyrocketing.fuyao.bot.mapper.group.GroupMemberMessageCountMapper.update] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Update]
2023-01-16 10:48:57.041  WARN 28060 --- [           main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "ninja.skyrocketing.fuyao.bot.pojo.group.GroupFunctionSettings".
2023-01-16 10:48:57.041  WARN 28060 --- [           main] c.b.m.core.injector.DefaultSqlInjector   : class ninja.skyrocketing.fuyao.bot.pojo.group.GroupFunctionSettings ,Not found @TableId annotation, Cannot use Mybatis-Plus 'xxById' Method.
2023-01-16 10:48:57.113  WARN 28060 --- [           main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "ninja.skyrocketing.fuyao.bot.mapper.user.UserCoinMapper".
2023-01-16 10:48:57.113  WARN 28060 --- [           main] c.b.m.core.injector.DefaultSqlInjector   : interface ninja.skyrocketing.fuyao.bot.mapper.user.UserCoinMapper ,Not found @TableId annotation, Cannot use Mybatis-Plus 'xxById' Method.
2023-01-16 10:48:57.159  INFO 28060 --- [           main] n.s.fuyao.FuyaoBotApplication            : Started FuyaoBotApplication in 2.339 seconds (JVM running for 2.767)
2023-01-16 10:48:57.181 DEBUG 28060 --- [           main] n.s.f.b.m.b.BotConfigMapper.selectById   : ==>  Preparing: SELECT config_name,config_value,add_date FROM bot_config WHERE config_name=?
2023-01-16 10:48:57.224 DEBUG 28060 --- [           main] n.s.f.b.m.b.BotConfigMapper.selectById   : ==> Parameters: qq_id(String)
2023-01-16 10:48:57.261  INFO 28060 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-01-16 10:48:57.288 ERROR 28060 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774) ~[spring-boot-2.7.5.jar!/:2.7.5]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755) ~[spring-boot-2.7.5.jar!/:2.7.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.7.5.jar!/:2.7.5]
	at ninja.skyrocketing.fuyao.FuyaoBotApplication.main(FuyaoBotApplication.java:38) ~[classes!/:4.5.20.86]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[fuyao-bot-4.5.20.86.jar:4.5.20.86]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[fuyao-bot-4.5.20.86.jar:4.5.20.86]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[fuyao-bot-4.5.20.86.jar:4.5.20.86]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[fuyao-bot-4.5.20.86.jar:4.5.20.86]
Caused by: org.springframework.jdbc.UncategorizedSQLException: 
### Error querying database.  Cause: java.sql.SQLException: No database selected
### The error may exist in ninja/skyrocketing/fuyao/bot/mapper/bot/BotConfigMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT config_name,config_value,add_date FROM bot_config WHERE config_name=?
### Cause: java.sql.SQLException: No database selected
; uncategorized SQLException; SQL state [3D000]; error code [1046]; No database selected; nested exception is java.sql.SQLException: No database selected
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92) ~[mybatis-spring-2.0.7.jar!/:2.0.7]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441) ~[mybatis-spring-2.0.7.jar!/:2.0.7]
	at jdk.proxy2/jdk.proxy2.$Proxy55.selectOne(Unknown Source) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:160) ~[mybatis-spring-2.0.7.jar!/:2.0.7]
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:89) ~[mybatis-plus-core-3.5.2.jar!/:3.5.2]
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148) ~[mybatis-plus-core-3.5.2.jar!/:3.5.2]
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89) ~[mybatis-plus-core-3.5.2.jar!/:3.5.2]
	at jdk.proxy2/jdk.proxy2.$Proxy57.selectById(Unknown Source) ~[na:na]
	at ninja.skyrocketing.fuyao.bot.service.impl.bot.BotConfigServiceImpl.getConfigValueByKey(BotConfigServiceImpl.java:29) ~[classes!/:4.5.20.86]
	at ninja.skyrocketing.fuyao.bot.config.MiraiBotConfig.runBot(MiraiBotConfig.java:44) ~[classes!/:4.5.20.86]
	at ninja.skyrocketing.fuyao.FuyaoBotApplication.run(FuyaoBotApplication.java:47) ~[classes!/:4.5.20.86]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-2.7.5.jar!/:2.7.5]
	... 11 common frames omitted
Caused by: java.sql.SQLException: No database selected
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-j-8.0.31.jar!/:8.0.31]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.0.31.jar!/:8.0.31]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[mysql-connector-j-8.0.31.jar!/:8.0.31]
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354) ~[mysql-connector-j-8.0.31.jar!/:8.0.31]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3446) ~[druid-1.2.15.jar!/:na]
	at com.alibaba.druid.wall.WallFilter.preparedStatement_execute(WallFilter.java:638) ~[druid-1.2.15.jar!/:na]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3444) ~[druid-1.2.15.jar!/:na]
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:434) ~[druid-1.2.15.jar!/:na]
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3444) ~[druid-1.2.15.jar!/:na]
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:152) ~[druid-1.2.15.jar!/:na]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:483) ~[druid-1.2.15.jar!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59) ~[mybatis-3.5.10.jar!/:3.5.10]
	at jdk.proxy3/jdk.proxy3.$Proxy87.execute(Unknown Source) ~[na:na]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64) ~[mybatis-3.5.10.jar!/:3.5.10]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79) ~[mybatis-3.5.10.jar!/:3.5.10]
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63) ~[mybatis-3.5.10.jar!/:3.5.10]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325) ~[mybatis-3.5.10.jar!/:3.5.10]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.5.10.jar!/:3.5.10]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109) ~[mybatis-3.5.10.jar!/:3.5.10]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89) ~[mybatis-3.5.10.jar!/:3.5.10]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151) ~[mybatis-3.5.10.jar!/:3.5.10]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145) ~[mybatis-3.5.10.jar!/:3.5.10]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140) ~[mybatis-3.5.10.jar!/:3.5.10]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76) ~[mybatis-3.5.10.jar!/:3.5.10]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427) ~[mybatis-spring-2.0.7.jar!/:2.0.7]
	... 21 common frames omitted

2023-01-16 10:48:57.291  INFO 28060 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closing ...
2023-01-16 10:48:57.295  INFO 28060 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closed

**Comment by NealLemonade** [comment]
> Reference in ne

后来有摸索着糊里糊涂建了一个但还是报错

**Comment by NealLemonade** [comment]
> @NealLemonade 你建了数据库没？

是不是要去改Application-dev.yml啊，我改了以后还是报错，感觉可能是没改对

**Comment by NealLemonade** [comment]
> @NealLemonade 你建了数据库没？

2023-01-16 12:54:53.570  WARN 29464 --- [           main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "ninja.skyrocketing.fuyao.bot.pojo.group.GroupMemberMessageCount".
2023-01-16 12:54:53.570  WARN 29464 --- [           main] c.b.m.core.injector.DefaultSqlInjector   : class ninja.skyrocketing.fuyao.bot.pojo.group.GroupMemberMessageCount ,Not found @TableId annotation, Cannot use Mybatis-Plus 'xxById' Method.
2023-01-16 12:54:53.571  WARN 29464 --- [           main] c.b.m.core.injector.AbstractMethod       : [ninja.skyrocketing.fuyao.bot.mapper.group.GroupMemberMessageCountMapper.insert] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Insert]
2023-01-16 12:54:53.573  WARN 29464 --- [           main] c.b.m.core.injector.AbstractMethod       : [ninja.skyrocketing.fuyao.bot.mapper.group.GroupMemberMessageCountMapper.update] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Update]
2023-01-16 12:54:53.740  WARN 29464 --- [           main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "ninja.skyrocketing.fuyao.bot.pojo.group.GroupFunctionSettings".
2023-01-16 12:54:53.741  WARN 29464 --- [           main] c.b.m.core.injector.DefaultSqlInjector   : class ninja.skyrocketing.fuyao.bot.pojo.group.GroupFunctionSettings ,Not found @TableId annotation, Cannot use Mybatis-Plus 'xxById' Method.
2023-01-16 12:54:53.830  WARN 29464 --- [           main] c.b.m.core.metadata.TableInfoHelper      : Can not find table primary key in Class: "ninja.skyrocketing.fuyao.bot.mapper.user.UserCoinMapper".
2023-01-16 12:54:53.830  WARN 29464 --- [           main] c.b.m.core.injector.DefaultSqlInjector   : interface ninja.skyrocketing.fuyao.bot.mapper.user.UserCoinMapper ,Not found @TableId annotation, Cannot use Mybatis-Plus 'xxById' Method.
2023-01-16 12:54:53.874  INFO 29464 --- [           main] n.s.fuyao.FuyaoBotApplication            : Started FuyaoBotApplication in 1.962 seconds (JVM running for 2.378)
2023-01-16 12:54:54.152 DEBUG 29464 --- [           main] n.s.f.b.m.b.BotConfigMapper.selectById   : ==>  Preparing: SELECT config_name,config_value,add_date FROM bot_config WHERE config_name=?
2023-01-16 12:54:54.167 DEBUG 29464 --- [           main] n.s.f.b.m.b.BotConfigMapper.selectById   : ==> Parameters: qq_id(String)
2023-01-16 12:54:54.177 DEBUG 29464 --- [           main] n.s.f.b.m.b.BotConfigMapper.selectById   : <==      Total: 0
2023-01-16 12:54:54.180  INFO 29464 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-01-16 12:54:54.206 ERROR 29464 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774) ~[spring-boot-2.7.5.jar!/:2.7.5]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755) ~[spring-boot-2.7.5.jar!/:2.7.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.7.5.jar!/:2.7.5]
	at ninja.skyrocketing.fuyao.FuyaoBotApplication.main(FuyaoBotApplication.java:38) ~[classes!/:4.5.20.86]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[fuyao-bot-4.5.20.86.jar:4.5.20.86]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[fuyao-bot-4.5.20.86.jar:4.5.20.86]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[fuyao-bot-4.5.20.86.jar:4.5.20.86]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[fuyao-bot-4.5.20.86.jar:4.5.20.86]
Caused by: java.lang.NullPointerException: Cannot invoke "ninja.skyrocketing.fuyao.bot.pojo.bot.BotConfig.getConfigValue()" because the return value of "ninja.skyrocketing.fuyao.bot.mapper.bot.BotConfigMapper.selectById(java.io.Serializable)" is null
	at ninja.skyrocketing.fuyao.bot.service.impl.bot.BotConfigServiceImpl.getConfigValueByKey(BotConfigServiceImpl.java:29) ~[classes!/:4.5.20.86]
	at ninja.skyrocketing.fuyao.bot.config.MiraiBotConfig.runBot(MiraiBotConfig.java:44) ~[classes!/:4.5.20.86]
	at ninja.skyrocketing.fuyao.FuyaoBotApplication.run(FuyaoBotApplication.java:47) ~[classes!/:4.5.20.86]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-2.7.5.jar!/:2.7.5]
	... 11 common frames omitted

2023-01-16 12:54:54.209  INFO 29464 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closing ...
2023-01-16 12:54:54.211  INFO 29464 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closed

鼓捣了一通以后这样，实在尽力了
